apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/awsdevopsssp/kind-infra
  ref:
    branch: develop
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/  