apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '1.0'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1